### ISSUE TITLE
different number of results???

### ISSUE THREAD

**Issue by TasnimGh** [ElsevierDev/elsapy#53]
Why is the number different between doc_srch.results and doc_srch.tot_num_res?

I read the explanation for the two functions, but I did not understand the difference.

**Comment by ale-de-vries** [comment]
The search indexes for ScienceDirect and Scopus _give access_ to only the first 5-6,000 results or so for any given search query, even if the number of items in the index is higher than that. E.g. if you search on 'cancer' in ScienceDirect (https://www.sciencedirect.com/search?qs=cancer), you will see that there are over 2 million results (below). But when you start navigating from the first results page to the next, and so on and so on, you will notice that you can't navigate beyond the first 6,000 results (see second screenshot).

The elsapy SDK has that same limitation. tot_num_res is the number of documents meeting your search query that exist in the online search index; num_res is the number of results that have actually been downloaded from the API and stored in your local search object. Because of the limitation explained above, num_res can never be higher than 5-6,000

![image](https://user-images.githubusercontent.com/19161701/88100440-8796cb80-cb6a-11ea-8de8-e62d71f3bc88.png)
![image](https://user-images.githubusercontent.com/19161701/88100650-d17fb180-cb6a-11ea-8afa-d2dd37f886a6.png)
